"""LLM service supporting mock and OpenAI-compatible backends."""

from __future__ import annotations

import json
import re
from typing import Any

import httpx

from app.core.config import get_settings
from app.schemas.intake import IntakeRequest
from app.schemas.llm_output import LLMOutput


VALID_PRIORITIES = {"low", "medium", "high"}
VALID_ROUTES = {"sales", "ops", "support", "product"}


def build_prompt(payload: IntakeRequest) -> str:
    """Build a constrained prompt requiring strict JSON output."""
    return (
        "You are an operations triage assistant.\n"
        "Return ONLY valid JSON with keys: summary, action_items, priority, route_to, confidence, reasoning_short.\n"
        "Rules:\n"
        "- priority must be one of low, medium, high.\n"
        "- route_to must be one of sales, ops, support, product.\n"
        "- action_items must be an array of short strings.\n"
        "- confidence must be between 0 and 1.\n"
        f"Input source_type: {payload.source_type}\n"
        f"Input source_system: {payload.source_system}\n"
        f"Input content: {payload.content}\n"
        f"Input tags: {', '.join(payload.tags) if payload.tags else 'none'}\n"
    )


def _sanitize_action_items(items: list[Any]) -> list[str]:
    cleaned: list[str] = []
    for item in items:
        text = str(item).strip()
        if text:
            cleaned.append(text)
    return cleaned[:5]


def parse_llm_json(raw_json: str) -> LLMOutput:
    """Parse and validate strict JSON output from the model."""
    data = json.loads(raw_json)
    priority = str(data.get("priority", "medium")).strip().lower()
    route_to = str(data.get("route_to", "ops")).strip().lower()

    if priority not in VALID_PRIORITIES:
        priority = "medium"
    if route_to not in VALID_ROUTES:
        route_to = "ops"

    confidence = data.get("confidence")
    if confidence is not None:
        try:
            confidence = max(0.0, min(1.0, float(confidence)))
        except (TypeError, ValueError):
            confidence = None

    summary = str(data.get("summary", "")).strip()
    if len(summary) < 10:
        summary = "Operational intake received and summarized for workflow routing."

    action_items = _sanitize_action_items(data.get("action_items", []))

    return LLMOutput(
        summary=summary,
        action_items=action_items,
        priority=priority,
        route_to=route_to,
        confidence=confidence,
        reasoning_short=str(data.get("reasoning_short", "")).strip() or None,
    )


def _mock_extract(payload: IntakeRequest) -> LLMOutput:
    text = payload.content.lower()
    priority = "medium"
    route_to = "ops"
    confidence = 0.74

    if any(token in text for token in ("outage", "urgent", "blocked", "escalation", "critical")):
        priority = "high"
        confidence = 0.89
    elif any(token in text for token in ("later", "next month", "backlog")):
        priority = "low"
        confidence = 0.63

    if any(token in text for token in ("customer", "ticket", "support", "incident")):
        route_to = "support"
    elif any(token in text for token in ("lead", "proposal", "pricing", "deal", "crm")):
        route_to = "sales"
    elif any(token in text for token in ("bug", "feature", "roadmap", "release")):
        route_to = "product"
    else:
        route_to = "ops"

    action_items = []
    for sentence in re.split(r"[.!?]\s*", payload.content.strip()):
        cleaned = sentence.strip()
        if cleaned:
            action_items.append(f"Review: {cleaned[:110]}")
        if len(action_items) >= 3:
            break

    summary = f"{payload.source_type.replace('_', ' ').title()} triaged for {route_to} with {priority} priority."
    return LLMOutput(
        summary=summary,
        action_items=action_items or ["Review intake and assign an owner."],
        priority=priority,
        route_to=route_to,
        confidence=confidence,
        reasoning_short="Generated by deterministic mock classifier.",
    )


def _openai_extract(payload: IntakeRequest) -> LLMOutput:
    settings = get_settings()
    if not settings.llm_api_key:
        raise RuntimeError("LLM_API_KEY is required when LLM_MODE=openai")

    prompt = build_prompt(payload)
    headers = {
        "Authorization": f"Bearer {settings.llm_api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": settings.llm_model,
        "temperature": 0.1,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": "You produce strict JSON only."},
            {"role": "user", "content": prompt},
        ],
    }
    with httpx.Client(timeout=20.0) as client:
        response = client.post(
            f"{settings.llm_base_url.rstrip('/')}/chat/completions",
            headers=headers,
            json=body,
        )
        response.raise_for_status()
        parsed = response.json()
        content = parsed["choices"][0]["message"]["content"]
    return parse_llm_json(content)


def extract_structured_output(payload: IntakeRequest) -> LLMOutput:
    """Extract structured JSON output using configured LLM mode."""
    settings = get_settings()
    if settings.llm_mode.lower() == "openai":
        return _openai_extract(payload)
    return _mock_extract(payload)
